# Generated by Django 2.2.1 on 2019-06-21 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190621_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_meetups', to=settings.AUTH_USER_MODEL),
        ),
    ]
